# Generated by Django 4.2.4 on 2023-08-22 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseNetObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('arrears', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('country', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('street', models.CharField(max_length=50)),
                ('house', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('release_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Factory',
            fields=[
                ('basenetobject_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='retail_network.basenetobject')),
            ],
            options={
                'verbose_name': 'Завод',
                'verbose_name_plural': 'Заводы',
                'ordering': ['title'],
            },
            bases=('retail_network.basenetobject',),
        ),
        migrations.AddField(
            model_name='basenetobject',
            name='contacts',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='retail_network.contacts'),
        ),
        migrations.AddField(
            model_name='basenetobject',
            name='products',
            field=models.ManyToManyField(to='retail_network.product'),
        ),
        migrations.CreateModel(
            name='Retailer',
            fields=[
                ('basenetobject_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='retail_network.basenetobject')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='retail_network.factory')),
            ],
            options={
                'verbose_name': 'Розничная сеть',
                'verbose_name_plural': 'Розничные сети',
                'ordering': ['title'],
            },
            bases=('retail_network.basenetobject',),
        ),
        migrations.CreateModel(
            name='Entrepreneur',
            fields=[
                ('basenetobject_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='retail_network.basenetobject')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='retail_network.retailer')),
            ],
            options={
                'verbose_name': 'Предприниматель',
                'verbose_name_plural': 'Предприниматели',
                'ordering': ['title'],
            },
            bases=('retail_network.basenetobject',),
        ),
    ]
