# Generated by Django 4.2.4 on 2023-08-22 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('retail_network', '0002_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basenetobject',
            name='contacts',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='retail_network.contacts'),
        ),
    ]
