# Generated by Django 4.2.4 on 2023-08-22 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('retail_network', '0003_alter_basenetobject_contacts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basenetobject',
            name='arrears',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Задолженность'),
        ),
        migrations.AlterField(
            model_name='basenetobject',
            name='contacts',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='retail_network.contacts', verbose_name='Контакты'),
        ),
        migrations.AlterField(
            model_name='basenetobject',
            name='date_created',
            field=models.DateField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='basenetobject',
            name='products',
            field=models.ManyToManyField(to='retail_network.product', verbose_name='Товары'),
        ),
        migrations.AlterField(
            model_name='basenetobject',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='city',
            field=models.CharField(max_length=50, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='country',
            field=models.CharField(max_length=50, verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='house',
            field=models.CharField(max_length=50, verbose_name='Дом'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='street',
            field=models.CharField(max_length=50, verbose_name='Улица'),
        ),
        migrations.AlterField(
            model_name='entrepreneur',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='retail_network.retailer', verbose_name='Поставщик'),
        ),
        migrations.AlterField(
            model_name='product',
            name='model',
            field=models.CharField(max_length=50, verbose_name='Модель'),
        ),
        migrations.AlterField(
            model_name='product',
            name='release_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата выхода'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='retailer',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='retail_network.factory', verbose_name='Поставщик'),
        ),
    ]
